// vuejs-auth0/src/components/Callback.vue
<template>
  <div>
    <AppNav/>
    Processing authentication response...
  </div>
</template>

<script>
import AppNav from "./AppNav";
import { parseHash } from "../utils/auth";

export default {
  beforeMount() {
    parseHash();
    window.location.href = window.location.origin;
  },
  components: {
    AppNav
  },
  name: "Callback"
};
</script>

<style scoped>
</style>

// react-auth0/src/components/Callback.js
import React, { Component } from "react";
import { parseHash } from "../utils/auth";

class Callback extends Component {
  componentDidMount() {
    parseHash();
    window.location.href = window.location.origin;
  }

  render() {
    return (
        <div>Reticulating splines...</div>
    )
  }
}

export default Callback;
